name: Archiver CI

on:
  push:
    branches: 
      - '**'
  pull_request:
      - '**'

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
